#!/usr/bin/env bash
SCRIPT_DIR=$(cd $(dirname $0); pwd)
cd $SCRIPT_DIR
sfdx force:org:create edition=developer -a test
sfdx force:user:password:generate -u test
sfdx force:source:push -u test
sfdx force:user:permset:assign -n Z_InhouseApplicationPermset -u test
sfdx force:data:tree:import -u test -f $SCRIPT_DIR/data/Z_Expense__c-Z_ExpenseItem__c.json
